### ISSUE TITLE
Leading zero when `numbering` is set to "1"

### ISSUE THREAD

**Issue by harrysw1729** [sahasatvik/typst-theorems#37]
Please consider the following minimal example.

```typst
#import "theorems.typ": *
#show: thmrules

#let proposition = thmbox("proposition", "Proposition").with(numbering: "1")

#proposition[
  This is a proposition.
]

```
<img width="238" alt="image" src="https://github.com/user-attachments/assets/1d6b8567-15a3-42bb-b538-f05fa3ca90e9">

In the rendered PDF, the displayed number of the proposition is "01". How should I get rid of the leading zero in this case, i.e., "Proposition 1"?

My Typst version is `0.11.1`. Thanks a lot for your help!

**Comment by jbirnick** [comment]
I hope people don't get annoyed by my advertising, but because nobody has been commenting/fixing for a week, I'm gonna recommend [great-theorems](https://typst.app/universe/package/great-theorems), which separates the counter functionality from the theorem functionality.

For the counter functionality you can use one of the two packages [rich-counters](https://typst.app/universe/package/rich-counters) or [headcount](https://typst.app/universe/package/headcount), and  in particular the counters should work perfectly.

**Comment by sahasatvik** [comment]
You can set `base: none`, say
```typst
#let proposition = thmbox("proposition", "Proposition", base: none)
```
